### ISSUE TITLE
请问你们的Example是用来演示该sdk的功能的吗？

### ISSUE THREAD

**Issue by SeasonLeee** [leancloud/Realtime-SDK-Flutter#107]
我看了main.dart里面都是一堆的unit test...

包括运行起来的界面也没有明显的可以demonstrate how this sdk works的选项....

请问该example没有demo sdk的功能的是吗？

那是不是想要测试你们的sdk只有按照你们的那个tutorial来集成到我们的项目里面来使用才知道呢？

**Comment by SeasonLeee** [comment]
一个Example的主要作用应该是一个对你们这个sdk的最基础功能的演示，但是现在运行了Example之后我盯着这一列的unit test我是有些不知所措的

**Comment by weakish** [comment]
example 更侧重演示某个方法该怎么调用。这里有一个简单的聊天应用的 demo 可供参考 https://github.com/SXiaoXu/FlutterRealtimeDemo/

**Comment by SeasonLeee** [comment]
好的谢谢分享，个人认为，某个方法怎么使用这些应该是交给文档的，Example里面就放最basic的sdk的使用，突出sdk的主要功能这样，也让使用者能够有最直接的感受来衡量你们这个工具跟其他平台工具的差异。

我关闭了。
