### ISSUE TITLE
在原生的sdk中，缓存这个功能是有的，然后该sdk是基于双端原生sdk的，那么问题是在flutter上面为什么没有开放/封装缓存功能呢？

### ISSUE THREAD

**Issue by SeasonLeee** [leancloud/Realtime-SDK-Flutter#109]
或者是，有没有排期加上该功能？

因为如果sdk能够提供该功能的话就完美了... 😅

否则的话我需要用sqlite进行消息的缓存然后判断过期等等操作.... 既然都是基于原生sdk的, 把这个也加上呗😅

谢谢！

**Comment by weakish** [comment]
因为 Java SDK 和 swfit SDK 各自实现了一套针对 Andorid/iOS 平台的缓存机制，所以 flutter 目前没有实现缓存功能。这个暂时还没有明确的排期。

**Comment by SeasonLeee** [comment]
好的谢谢，不过我有理解这个缓存是有做对应平台的实现的。

只要疑问是，我有看到flutter sdk中是有通过MethodChannel，建立了与原生plugin的bridge的... 那么在这个前提下，为何不直接利用plugin已经有的缓存的机制呢，通过这个bridge来获取结果之类的

https://github.com/leancloud/Realtime-SDK-Flutter/blob/c7f5748b2ef4bef69fa94ff9f4db9921d028ad0e/lib/src/client.dart#L10

同时我也发现好像duplicate #85 了。。

**Comment by SeasonLeee** [comment]
考虑到duplicate, 我把这个关闭，并把对话都转移到 #85 上。
