### ISSUE TITLE
当在一个widget里面通过执行client.onMessage监听新消息的接收后，该widget的销毁该监听还在持续。

### ISSUE THREAD

**Issue by SeasonLeee** [leancloud/Realtime-SDK-Flutter#115]
问题的描述如上。

比如我在页面A需要进行监听新的消息并对其做操作。但是我离开页面A之后，该监听应该不再执行。
（该页面具体到flutter就是一个widget的销毁(dispose), 正常来讲，正在工作的widget里面的所有controller, listener会在dispose生命周期函数中进行清理)

目前sdk中的client里面貌似都没有可以取消该监听的行为的方法。

**Comment by zapcannon87** [comment]
试一试 `client.onMessage = null;` ？

**Comment by SeasonLeee** [comment]
![image](https://user-images.githubusercontent.com/13610283/114007090-986fa480-9893-11eb-99c0-bc05bfc9ca40.png)

this is just awesome.........
