### ISSUE TITLE
RFC for API

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/Realtime-SDK-Flutter#33]
[SDK API Naming Reference](https://github.com/leancloud/Realtime-SDK-Flutter/wiki/SDK-API-Naming-Reference)

**Comment by jwfing** [comment]
feature | C request | S response/notification | obj-c | swift | java | javascript | dotNet | comment
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ----
登入/登出 | session/open | session/opened | xxx | xxx | IMClient#open | xxx | xxx | -
 | session/close | session/closed | xxx | xxx | IMClient#close | xxx | xxx | -
刷新 sessiontoken | session/refresh | session/refreshed | xxx | xxx | - | xxx | xxx | SDK 自动执行，不对外公开
对话功能 | conv/start | conv/started | xxx | xxx | IMClient#createConversation | xxx | xxx | xxx
 | conv/add | conv/added | xxx | xxx | Conversation#join | xxx | xxx | xxx
 | - | conv/joined | xxx | xxx | onInvited(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-joined | xxx | xxx | onMemberJoined(client, conv, members) | xxx | xxx | xxx
 | conv/remove | conv/removed | xxx | xxx | Conversation#quit | xxx | xxx | xxx
 | - | conv/left | xxx | xxx | onKicked(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-left | xxx | xxx | onMemberLeft(client, conv, members) | xxx | xxx | xxx
查询对话 | conv/query | conv/results | xxx | xxx | ConversationQuery#find | xxx | xxx | xxx
获取对话人数 | conv/count | conv/results | xxx | xxx | Conversation#getMemberCount | xxx | xxx | xxx
获取对话成员 | conv/members | conv/results | xxx | xxx | Conversation#getAllMemberInfo(offset, limit) | xxx | xxx | xxx
 | conv/members | conv/results | xxx | xxx | Conversation#getMemberInfo(clientId) | xxx | xxx | xxx
查询是否对话成员 | conv/is-member | conv/is-member | xxx | xxx | N/A(不支持) | xxx | xxx | xxx
修改对话数据 | conv/update | conv/updated | xxx | xxx | Conversation#updateInfoInBackground | xxx | xxx | xxx
 | - | conv/updated | xxx | xxx | onInfoChanged(client, conv, attr, operator) | xxx | xxx | xxx
更新某成员的对话属性 | conv/member-info-update | conv/member-info-updated | xxx | xxx | Conversation#updateMemberRole | xxx | xxx | xxx
 | - | conv/member-info-updated | xxx | xxx | onMemberInfoUpdated(client, conv, memberInfo, attr, operator) | xxx | xxx | xxx
开启离线推送通知 | conv/mute | conv/updated | xxx | xxx | Conversation#unmute | xxx | xxx | xxx
关闭离线推送通知 | conv/unmute | conv/updated | xxx | xxx | Conversation#mute | xxx | xxx | xxx
查询对话中成员接收消息状态 | conv/max-read | conv/max-read | xxx | xxx | N/A(不支持) | xxx | xxx | xxx
收发消息 | direct | ack | xxx | xxx | Conversation#sendMessage | xxx | xxx | xxx
消息通知 | - | direct | xxx | xxx | onMessage(msg, conv, client) | xxx | xxx | 收到新消息
消息回执通知 | - | rcp | xxx | xxx | onMessageReceipt(msg, operator, conv, client) | xxx | xxx | 通知里面无 read 标记，表示消息被接收，会同时触发 onMessageReceipt 和 onLastDeliveredAtUpdated 回调
 | - | rcp | xxx | xxx | onLastDeliveredAtUpdated(client, conv) | xxx | xxx | 通知里面无 read 标记，表示消息被接收，会同时触发 onMessageReceipt 和 onLastDeliveredAtUpdated 回调
未读消息通知 | - | unread | xxx | xxx | onUnreadMessagesCountUpdated(client, conv) | xxx | xxx | 客户端刚上线时，云端会下发未读数的通知
客户端清除未读通知 | read | - | xxx | xxx | Conversation#read | xxx | xxx | xxx
 | - | rcp | xxx | xxx | onLastReadAtUpdated(client, conv) | xxx | xxx | 通知里面有 read 标记，会触发 onLastReadAtUpdated 回调
查询历史消息 | logs | logs | xxx | xxx | Conversation#queryMessages | xxx | xxx | xxx
消息修改与撤回 | patch/modify | patch/modified | xxx | xxx | Conversation#recallMessage / Conversation#updateMessage | xxx | xxx | xxx
 | - | patch/modified | xxx | xxx | onMessageUpdated / onMessageRecalled | xxx | xxx | xxx
黑名单 | blacklist/block | blacklist/blocked | xxx | xxx | Conversation#blockMembers(members) | xxx | xxx | xxx
 | - | conv/blocked | xxx | xxx | onBlocked(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-blocked | xxx | xxx | onMemberBlocked(client, conv, members, operator) | xxx | xxx | xxx
黑名单 | blacklist/unblock | blacklist/unblocked | xxx | xxx | Conversation#unblockMembers(members) | xxx | xxx | xxx
 | - | conv/unblocked | xxx | xxx | onUnblocked(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-unblocked | xxx | xxx | onMemberUnblocked(client, conv, members, operator) | xxx | xxx | xxx
查询黑名单 | blacklist/query | blacklist/query-result | xxx | xxx | Conversation#queryBlockedMembers(offset, limit) | xxx | xxx | xxx
校验黑名单 | blacklist/check-block | blacklist/check-result | xxx | xxx | N/A(不支持) | xxx | xxx | xxx
禁言 | conv/add-shutup | conv/shutup-added | xxx | xxx | Conversation#muteMembers(members) | xxx | xxx | xxx
 | - | conv/shutuped | xxx | xxx | onMuted(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-shutuped | xxx | xxx | onMemberMuted(client, conv, members, operator) | xxx | xxx | xxx
取消禁言 | conv/remove-shutup | conv/shutup-removed | xxx | xxx | Conversation#unmuteMembers | xxx | xxx | xxx
 | - | conv/unshutuped | xxx | xxx | onUnmuted(client, conv, operator) | xxx | xxx | xxx
 | - | conv/members-unshutuped | xxx | xxx | onMemberUnmuted(client, conv, members, operator) | xxx | xxx | xxx
查询禁言列表 | conv/query-shutup | conv/shutup-result | xxx | xxx | Conversation#queryMutedMembers(offset, limit) | xxx | xxx | xxx
校验禁言 | conv/check-shutup | conv/check-result | xxx | xxx | N/A(不支持) | xxx | xxx | xxx
主动驱离 | - | goaway | xxx | xxx | xxx | xxx | xxx | xxx
