### ISSUE TITLE
会话查询有概率不返回LastMessage

### ISSUE THREAD

**Issue by datang** [leancloud/Realtime-SDK-Flutter#62]
```
ConversationQuery query = client.conversationQuery();
query.whereString = '{\"m\":\"${client.id}\"}';
query.limit = 50;
query.skip = 0;
query.excludeMembers = false;
query.includeLastMessage = true;
List<Conversation> conversations = await query.find();
```

确实设置了includeLastMessage=true，但返回结果中仍然有很大概率不存在LastMessage。

**Comment by zapcannon87** [comment]
> 但返回结果中仍然有很大概率不存在LastMessage。

大概率是指：同一个会话（含有历史消息），使用 includeLastMessage 查询它，查询结果有时有 LastMessage，有时没有 LastMessage，这样？

另外，这个情况是 iOS 端和 Android 端都存在吗？

**Comment by datang** [comment]
只尝试了Android端，会出现这种情况。
后来发现每次请求查询之前重新执行client.close();client.open()可以正常返回LastMessage。

**Comment by zapcannon87** [comment]
@jwfing

**Comment by jwfing** [comment]
使用 6.5.3 （含）版本以上的 java unified sdk。
