### ISSUE TITLE
好奇你们在开发SDK的时候是如何测试的？有没有同时做出一套简单的UI？

### ISSUE THREAD

**Issue by Wing-Li** [leancloud/Realtime-SDK-Flutter#63]
还是就直接使用代码来测试是否接收到消息的？

如果有简单的UI，可不可以将UI也开放出来呢?

**Comment by zapcannon87** [comment]
[example](https://github.com/leancloud/Realtime-SDK-Flutter/tree/master/example) 就是一个完整的 runtime-test-app，同时也可以作为 API 使用参考。
