### ISSUE TITLE
对外接口上需注意的一些问题- IMClient open 的参数

### ISSUE THREAD

**Issue by jwfing** [leancloud/Realtime-SDK-Flutter#9]
现在有一个名为 force 的参数，这个标记是表示是否要踢掉其他同样 id+tag 组合的设备。

RTM Server 端的设想是这样的：
1. session open 命令有一个 r 参数，表示是否重连。默认为 false。
1. 如果 session open 的时候，带了 tag，那么相同 clientId（以后记为 id）+tag 组合的设备只保留最新连上来的设备（老的会被踢掉）。如果不带 tag，不会发生互相踢的情况。
2. SDK 内部有自动重连机制，此时如果是被踢掉的设备进行了自动重连，它应该不能挤掉其他设备（因为是 SDK 内部机制，优先级不能高于用户手动的操作）。

所以，tag 这种机制是专门设计来进行排他登录用的，应用层在登录的时候，传了 id+tag，这时候会产生排他的副作用。如果业务上没有这种需求，那么就不需要 tag，这时候 r 参数怎么设都不起作用。

针对 tag 有效的场景，设想的使用流程是：
1. 设备 a 使用 id + tag 登录；
1. 设备 b 使用同样的 id+tag 登录，这时设备 a 会被踢下线；
2. 设备 a 客户端内会提示终端用户，ta 在其他地方有登录，当前设备下线了。同时 SDK 开始自动重连的尝试（r 为 true），但是会失败。
3. 设备 a 上的用户要么不再登录，要么重新登录（把设备 b 挤下线）。

所以对外接口上，force 参数改为 reconnect 会更好理解。现在 js /java sdk 都只有 reconnect 标记了，oc sdk 是 reconnect/force 二选一，我们对外接口都统一到 reconnect 吧。
1. https://leancloud.github.io/js-realtime-sdk/docs/Realtime.html#createIMClient
1. https://leancloud.cn/api-docs/iOS/Constants/AVIMClientOpenOption.html

**Comment by leeyeh** [comment]
既然 reconnect = false 的情况只有内部用到，是不是直接去掉这个参数好了，只要传了 tag 就认为是要踢别的设备下线的。

**Comment by jwfing** [comment]
也就是说，对开发者来说，没有 force 这种说法，应用里面显示调用的，就都是要去挤掉别人的，只有一个是否为重连的标记（这好像也多半是 sdk 内部使用的）。

**Comment by jwfing** [comment]
@leeyeh 不知道当时为什么还要有一个 reconnect 标记，我也觉得应该只是 SDK 内部使用而已，不清楚是否有应用层要重连的。

**Comment by zapcannon87** [comment]
> 设备 a 客户端内会提示终端用户，ta 在其他地方有登录，当前设备下线了。同时 SDK 开始自动重连的尝试（r 为 true），但是会失败。

设备 a 被下线后，SDK 不应该执行重连逻辑，SDK 是可以做到的，且这才是更符合用户逻辑的行为。

**Comment by zapcannon87** [comment]
> 不知道当时为什么还要有一个 reconnect 标记，我也觉得应该只是 SDK 内部使用而已，不清楚是否有应用层要重连的。

并不是，这是用户能用到的，且目前市场有现实用例的场景（微信单设备登陆，可以自行感受一下）。

相关示例代码这里有，[link1](https://github.com/leancloud/swift-sdk-demo/blob/d1e20d234f329ba4a519fd98bbab8af4a832a9d7/swift-sdk-demo/Chat/LaunchViewController.swift#L33), [link2](https://github.com/leancloud/swift-sdk-demo/blob/d1e20d234f329ba4a519fd98bbab8af4a832a9d7/swift-sdk-demo/Chat/LaunchViewController.swift#L111)

**Comment by zapcannon87** [comment]
而且这个接口本来就[改过一次了](https://github.com/leancloud/rfcs/issues/987)，现在大家对这一块有疑惑，是应为我们的即时通讯文档缺少相关说明。

SDK 的接口设计是没有问题的。

**Comment by jwfing** [comment]
其实，这个 issue 的目的是，force 这个名字要改成 reconnect。

**Comment by zapcannon87** [comment]
用服务端的逻辑来解释就是：

发出 session open 之后，client 得到的回调有可能是 session close (code == 4111)。然后 client 需要把这个异常抛给用户，让用户来决定后续的逻辑。

**Comment by zapcannon87** [comment]
force 和 reconnect 就是互斥的意思而已。总之 SDK 提供的对外接口肯定要有这么一个东西。

名称该来该去，我觉得没有太大意义。

**Comment by zapcannon87** [comment]
如果觉得 force 这个借口命名不太好，要改，我也没有意见。

但是 open 时的 force/reconnect 参数是肯定要保留的，这涉及到功能的完备性。

**Comment by jwfing** [comment]
reconnect 为 true/false 就可以了啊，使用 reconnect 这样文档好写。

**Comment by zapcannon87** [comment]
接口改名我没意见啊。

我有异议的只针对「觉得 force/reconenct 只是 SDK 内部使用」，用户是有使用的需求的。

**Comment by zapcannon87** [comment]
因为 client.open 接口是叫 `open`，所以参数名称用 `reopen` 是不是更好一点？
